// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wemljbimllqhmdcpbkmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlbWxqYmltbGxxaG1kY3Bia216Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MzM0NjIsImV4cCI6MjA3MjIwOTQ2Mn0.9qT2wrfHseCAxTpHmEWVx3lVbe83TcUDIrY5s04rOT4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});