
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://indwosuuyjfhwvovmpdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImluZHdvc3V1eWpmaHd2b3ZtcGRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3ODAwMjgsImV4cCI6MjA1NzM1NjAyOH0.s6CDFyA-7KZLWDqgj4ePXwxCUaJYldFM6AcoxZ8rYL4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Check connection
(async () => {
  try {
    console.log("Checking Supabase connection...");
    const { data, error } = await supabase.from('login').select('count');
    
    if (error) {
      console.error("Supabase connection error:", error.message);
    } else {
      console.log("Supabase connection successful:", data);
    }

    // Also check if auth is working
    const { data: authData, error: authError } = await supabase.auth.getSession();
    if (authError) {
      console.error("Supabase auth error:", authError.message);
    } else {
      console.log("Supabase auth initialized:", authData.session ? "Active session" : "No active session");
    }
  } catch (err) {
    console.error("Supabase connection failed:", err);
  }
})();
